name: Next.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      # Set up Node.js using the version specified in the matrix
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Next.js app
      - name: Build
        run: npm run build
